config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brand_id, :brand_name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Ürün başarıyla oluşturuldu.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Ürün başarıyla güncellendi.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Ürün başarıyla silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_id, :product_name, :brand_id, :model)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Marka %>
    <%= form.text_field :brand_name %>
  </div>

  <div class="actions">
    <%= form.submit :Oluştur %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Markayı Düzenle</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Göster', @brand %> |
<%= link_to 'Geri', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Markalar</h1>

<table>
  <thead>
    <tr>
      <th>Marka</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brand_name %></td>
        <td><%= link_to 'Göster', brand %></td>
        <td><%= link_to 'Düzenle', edit_brand_path(brand) %></td>
        <td><%= link_to 'Sil', brand, method: :delete, data: { confirm: 'Emin misiniz ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Marka', new_brand_path %>

app/views/brands/new.html.erb
<h1>Yeni Marka</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Geri', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marka:</strong>
  <%= @brand.brand_name %>
</p>


<%= link_to 'Düzenle', edit_brand_path(@brand) %> |
<%= link_to 'Geri', brands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <! — Latest compiled and minified CSS →
  </head>

  <body>
    <div class="sidebar">
      <h1>
        <a ><%= link_to "Marka", brands_path %></a>
        <a><%= link_to "Ürün", products_path %></a>
      </h1>
    </div>
    </br>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Ad %>
    <%= form.text_field :product_name %>
  </div>

  <div class="control-group">
    <%= form.label :Marka, class: 'control-label' %>
    <div class="controls">
      <%= collection_select( :product, :brand_id, Brand.all, :id, :brand_name, {}, { :multiple => false } ) %>
    </div>
  </div>
  </br>
  <div class="field">
    <%= form.label :Model %>
    <%= form.text_field :model %>
  </div>

  <div class="actions">
    <%= form.submit :Oluştur%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Ürünü Düzenle</h1>

<%= render 'form', product: @product %>

<%= link_to 'Göster', @product %> |
<%= link_to 'Geri', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ürünler</h1>

<table>
  <thead>
    <tr>
      <th>Ad</th>
      <th>Marka Id</th>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.brand_id %></td>
        <td><%= product.model %></td>
        <td><%= link_to 'Göster', product %></td>
        <td><%= link_to 'Düzenle', edit_product_path(product) %></td>
        <td><%= link_to 'Sil', product, method: :delete, data: { confirm: 'Emin misiniz ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Ürün', new_product_path %>

app/views/products/new.html.erb
<h1>Yeni Ürün</h1>

<%= render 'form', product: @product %>

<%= link_to 'Geri', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ad:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Marka Id:</strong>
  <%= @product.brand_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<%= link_to 'Düzenle', edit_product_path(@product) %> |
<%= link_to 'Geri', products_path %>